name: ci 
on: push
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.414
      - name: Run with dotnet
        shell: bash
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/ciyuanhuixing/ToDoEmailNotification.git
          dotnet run -p ToDoEmailNotification/ToDoEmailNotification
          git clone https://${{ secrets.GH_TOKEN1 }}@github.com/zydhx/service.git
          cd service
          echo `date +"%Y-%m-%d %H:%M:%S"` >> 1.txt
          git config --global user.email "zydhx3@qq.com"
          git config --global user.name "Your zydhx"
          git add -A
          git commit -m "`date +"%Y-%m-%d %H:%M:%S"`"
          git push


